#!/bin/sh

cat /etc/passwd | sed /^#/d'' | sed -n "2, \$p" | awk -F: '{print $1}' | sort -r  | awk -v FT_LINE1="$FT_LINE1" -v FT_LINE2="$FT_LINE2" '{ if (NR>=FT_LINE1 && NR<=FT_LINE2) print $1 }' | tr '\n' ','

